Ess adding in house functionalities
SciCatProject/pyscicat pull request #10
Opened 2022-02-17 10:19 UTC by nitrosx

THis pull adds to the official main branch in the SciCat project the changes that we have implemented in-house at ESS.

The code is still a work in progress and needs mroe testing.

2022-02-17 10:25 UTC, nitrosx commented
I forgot about the linting. Will work on it and update this PR

2022-02-17 16:53 UTC, dylanmcreynolds requested changes
Awesome stuff, thanks!

I added a couple of small comments.

Also, we should add unit tests for your new methods. 

https://github.com/SciCatProject/pyscicat/blob/main/pyscicat/tests/test_client.py

There's not a ton of logic in there, but the requests mock code can at least verify that we're pointing to the correct URL and test what logic is in there.

2022-02-17 16:53 UTC, dylanmcreynolds commented on pyscicat/client.py
> +                headers=self._headers,
I think that we should choose one or the other for sending the token, either as a query param or as a header. I can't remember why you preferred headers, but they are equal to me. So, can you remove the `access_token` query parameter?

2022-02-17 16:56 UTC, dylanmcreynolds commented
Also, can you please look into adding documentation at https://github.com/SciCatProject/pyscicat/tree/main/docs/source? Maybe a couple of how to documents about getting proposals and instruments? I think the API calls you added will get auto generated, but we should check.

2022-02-21 10:41 UTC, nitrosx commented on pyscicat/model.py
> +class OrigDatablock(Ownable):
Possibly!!!
I would say that we should follow what is done in SciCat backend for these two models.
I check and come back on this.

2022-02-21 10:47 UTC, nitrosx commented on pyscicat/client.py
> +                headers=self._headers,
@dylanmcreynolds : current SciCat backend uses access_token, while the nestJs implementation is using headers. 
Given that soon we are migrating to the new one, and we, at ESS, are already testing the new implementation, I thought that it would be nice not to worry configuring pySciCat to work with a specific backend, but make it transparent. 
That's the reason why I left both of them.

That said, I understand that it would be less confusing to use only one method. 
Would you prefer to have a parameter when you instantiate the class that select which authentication model to use?
We could discuss at the next SciCat meeting

2022-02-21 10:48 UTC, nitrosx commented
I will look into the documentation

2022-02-21 15:09 UTC, nitrosx commented on pyscicat/model.py
> +class OrigDatablock(Ownable):
@dylanmcreynolds I just checked on SciCat backend. The two models do not have any relation, but they do have some of the same fields. Possibly we can change the code and make Datablock inherit from origDatablock.
Thoughts?

2022-02-22 15:02 UTC, dylanmcreynolds commented on pyscicat/model.py
> +class OrigDatablock(Ownable):
I assume that this this is an oversight on the server, but for only three fields I'm not going to worry about it, I think.

2022-02-22 16:54 UTC, dylanmcreynolds commented on pyscicat/client.py
> +                headers=self._headers,
Let's leave as you have done it in this PR for now. I have submitted an issue asking whether the nest.js backend should accept both methods here: https://github.com/SciCatProject/backend/issues/592

2022-02-23 07:32 UTC, nitrosx commented on pyscicat/client.py
> +                headers=self._headers,
I will check with Henrik, but I think nestjs implementation accept authentication only in the header, in the format:
`Authentication: Bearer <token>``

2022-02-23 16:21 UTC, dylanmcreynolds commented on pyscicat/client.py
> +                headers=self._headers,
Yes. I added an issue in backend to see if we can add the query parameter. There are probably numerous client code bases already that will be affected by this change.

2022-02-24 08:24 UTC, nitrosx commented on pyscicat/model.py
> +class OrigDatablock(Ownable):
I agree. I think we should change it first in the backend, than refactor the code here accordingly

2022-02-24 08:29 UTC, nitrosx commented
@dylanmcreynolds : I'm going to test pyScicat in a use case. I will have the examples to insert in the documentation once I'm done with that. I think it will take few days.
Do you want to wait for that to merge or should we go ahead merge and do another PR when I have the examples ready?

2022-03-08 12:46 UTC, nitrosx commented
@dylanmcreynolds : I updated the documentation as you requested.

2022-03-09 10:03 UTC, nitrosx commented
@dylanmcreynolds : is it ok if we merge this PR and I work and include testing in a new PR?

2022-03-09 17:48 UTC, dylanmcreynolds commented on docs/source/howto/ingestion_simulation_dataset_ess.md
> +            ... omissed ...
In English, the word is "omitted"

2022-03-09 18:38 UTC, dylanmcreynolds commented
Thanks for the documentation!

The way it is right now, your hard work is not yet viewable in the documentation. 

Check out this https://github.com/SciCatProject/pyscicat/blob/b901bac087c7dde342589a58d3f4d689e350dcb3/docs/source/index.md?plain=1#L17

We could either add your documents as an and entry in "How To", or make a new category in the TOC called "Examples" for this documentation. What do you think?

BTW, this should be better documented, but to test the documentation build locally:

If you have not done so yet in your environment, setup the dev requirements to get the sphinx build code:
```
pip install -r requirements-dev.txt
```

Then:
```
cd docs
make html
```
This will build the web site locally into `docs/build/html`, and you can open a browser to the index.html

2022-03-10 12:33 UTC, nitrosx commented
@dylanmcreynolds : I added our example under the "How-to" section.
I fixed the json code in the document, so it builds.
I also added packages _pydantic_ and _requests_ in requirements-dev.txt, so to build the documentation the following instructions will suffice:
`
pip install -r requirements-dev.txt
cd docs
make html
`

2022-03-10 16:53 UTC, dylanmcreynolds commented
Sorry, my instructions assumed that you had already run: 

```
pip install -r requirements.txt
```
People tend treat requirements-dev.txt as "add-ons to the primary package". I'd rather not have dependencies repeeated in different files. Can you please remove this?

2022-03-11 06:29 UTC, nitrosx commented
No problem. Done!!!
We should include this info in the documentation. New ticket?

2022-03-11 16:14 UTC, dylanmcreynolds commented
> We should include this info in the documentation. New ticket?

Yes, good idea:
https://github.com/als-computing/pyscicat/issues/6

2022-03-14 15:05 UTC, merged