More upload functions
SciCatProject/pyscicat pull request #35
Opened 2023-01-27 17:31 UTC by eilmiv

Closes #34

2023-01-27 18:09 UTC, dylanmcreynolds approved these changes
Thank you for the PR!

2023-01-27 18:16 UTC, dylanmcreynolds commented on pyscicat/client.py
> +            pid (or unique identifier) of instrument being updated. By default, pid is taken from instrument parameter.
Oops. This line is too long for flake8. Can you add a new line?

2023-01-27 18:36 UTC, eilmiv commented on pyscicat/client.py
> +            pid (or unique identifier) of instrument being updated. By default, pid is taken from instrument parameter.
Yes, I forgot to run flake8. Thank you for the quick reply.

2023-01-30 08:14 UTC, nitrosx requested changes

2023-01-30 08:14 UTC, nitrosx commented on pyscicat/client.py
> +    def update_sample(self, sample: Sample, sampleId: str = None) -> str:
Can we change the name to this function to **_samples_update_** to be consistent with naming convention used with other endpoints?

2023-01-30 08:14 UTC, nitrosx commented on pyscicat/client.py
> +    def update_instrument(self, instrument: Instrument, pid: str = None) -> str:
Same as my previous comment, can we change the name to _**instruments_update**_?

2023-01-30 08:14 UTC, nitrosx commented on pyscicat/client.py
> +    def update_proposal(self, proposal: Proposal, proposalId: str = None) -> str:
Same as before, can we rename it **_proposals_update_**?

2023-01-30 10:18 UTC, eilmiv commented on pyscicat/client.py
> +    def update_sample(self, sample: Sample, sampleId: str = None) -> str:
Yes. I agree; this is better. (I was trying to be consistent with the update_dataset endpoint, as all the existing update functions that have a name starting with the endpoint are `_replace` functions, but from what I can tell the next backend no longer supports `replaceOrCreate` operations.)

2023-01-30 10:19 UTC, eilmiv commented on pyscicat/client.py
> +    def update_instrument(self, instrument: Instrument, pid: str = None) -> str:
See answer to [previous comment](https://github.com/SciCatProject/pyscicat/pull/35#discussion_r1090287857)

2023-01-30 10:19 UTC, eilmiv commented on pyscicat/client.py
> +    def update_proposal(self, proposal: Proposal, proposalId: str = None) -> str:
See answer to [previous comment](https://github.com/SciCatProject/pyscicat/pull/35#discussion_r1090287857)

2023-01-30 10:20 UTC, nitrosx commented on pyscicat/client.py
> +    def update_sample(self, sample: Sample, sampleId: str = None) -> str:
Update_dataset has been long overdue to be updated to the correct name, aka datasets_update.
Actually, would be so kind to update that one too?

2023-01-30 10:37 UTC, eilmiv commented on pyscicat/client.py
> +    def update_sample(self, sample: Sample, sampleId: str = None) -> str:
I updated it and kept the old name, like for the existing renamed functions.

2023-01-30 10:45 UTC, nitrosx approved these changes

2023-01-31 13:27 UTC, merged